title: Ptak49
email: kk@c66.pl
description: >- # this means to ignore newlines until "baseurl:"
  Sprzedam dom
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ptak49.c66.pl" 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
